### PR TITLE
Plot methods refactor

### PR DESCRIPTION
**Pull request by janssenhenning**
I had some free time over my vacation and as a small project I decided to take a look at the plot_methods. In this pull request I implemented a small system, which can be used to consistently and with not much effort consistently handle default values for plots, which can probably also be extended to the bokeh_plots.

In `vis/__init__.py` I implemented a base class for handling default values. It takes a dictionary of defined defaults and creates three copies:

- exact and unchanged copy of the defaults
- copy of the defaults which can be changed via the method set_defaults (always a single parameter set)
- copy of the current defaults which can be changed via set_parameters (can also contain a set of parameters for multiple plots)

The parameters (not the defaults) can be accessed and modified by indexing the class like a dictionary.

In `vis/matplotlib_plotter.py` there is a subclass of this base class which specifies the concrete matplotlib defaults. This class also has some matplotlib specific helper methods, like setting up the figure, setting scales, limits, saving, or extracting certain special subsets of the parameters (for figures and plots)

In plot_methods a instance of this matplotlibplotter is created at import and can be modified (via set_defaults_new and reset_defaults at the moment)

To ensure consistency of this object each plotting method has a decorator ensure_plotter_consistency, which makes sure that the parameters and defaults are not in a inconsistent state This does three things:

- if an error is thrown by the method it is caught by the decorator, each change that has been made to the object is reset and the error is raised
- after the execution of the method the parameters (so the last of the three copies) is reset to the current defaults
- it checks that the defaults have not changed during the execution of the method

I also started implementing more extensive tests of the plot_methods

There are still a lot of methods, which have to be converted to the new framework. I changed the interface of the methods slightly but all methods can still handle the old interface but will raise DeprecationWarnings

Maybe you can see the use of this system in the implementation for multiaxis_scatterplot I also added. This way you don't have to worry as much about the default values

@broeder-j @PhilippRue If you have some feedback let me know. I will just leave this pull request for now and maybe slowly convert more functions to this system

### CODE REVIEW

**Comment by broeder-j** [comment]
@janssenhenning Thanks for doing this, you are my hero! 
I have peeked at it so far. I need to test it in more detail for detailed feedback.
 
Thinks to consider (of most I think you have taken care):

- we want to allow for a given function type a different 'default set', i.e what marker, linetype, colors for example. 
The global set now is the same for all, but default arguments in the function signature override the global setting for it, right?
- in (some of) the plot functions we want to preserve the ability to parse *args and **kwargs, which we often use to expose all parameters of the underlying matplotlib/bokeh method (you took care of this by filtering out used kwargs). There one might have to  be careful with name clashes.
- all plot functions should return the axis, because this allows to add further plots onto the same axis, or embed the axis/plot into a figure layout of subplots, or a dashboard. (Which seems nicely preserved by your implementation.)
- These methods are mostly used by 'aiida-fleur.tools.plot.fleur' and of course in notebooks and evaluations.

For testing matplotlib plots there is a pytest plugin (https://github.com/matplotlib/pytest-mpl). I have not tried it so far, but I think philipp has. Maybe this can help us to get a better coverage of the plot_methods.

**Comment by janssenhenning** [comment]
@broeder-j To your points

1. Yes, that's true if you want to overwrite the default set (for example in mutli_scatter_plot the linestyle is set to '') you set the parameter in the function signature. But you have to remember to pipe this value into set_parameters as normally only the kwargs are passed in
2. I am still figuring out how to layout the parameter dict to minimize name clashes, but I could also implement a keyword like `extra_kwargs` with a dict which bypasses the Plotter object and goes directly into the underlying function
4. Yes, but I think once this implementation is matured it could also be useful for simplifying the kkr plotting functions in masci_tools. For example I already implemented the option of making area_plots with `fill_between` which was not possible before. 

I actually already started using pytest-mpl to test the functions I modified (see `test_plot_methods.py`)

**Comment by janssenhenning** [comment]
Update to this:
I decided to move away from making explicit copies of the parameter dictionary to a much cleaner solution utilizing the `ChainMap` object from the `collections` module. If you are not familiar with this it allows you to chain mappings (i.e. dictionaries) together with the lookups on this object going through each mapping until it finds a value. Setting a value goes to the top layer by default, but you can also modify the deeper layers. This allows us to define the global defaults and then stack different layers of mappings with set values on top depending, which should take precedence. I settled on 4 layers (Top to bottom)

1. Parameters passed into the function
2. Defaults defined by the function (e.g some functions want to have no lines by default)
3. Defaults defined by the user
4. Hardcoded fallbacks if nothing else is defined

The function defaults can be defined by a call to set_default() on the object with `default_type='function'` and global defaults with the same call and `default_type='global'  (default)`

**Comment by janssenhenning** [comment]
I now also have some understanding of how to test bokeh plots. Since we cannot really test the produced images, we can extract the produced json data, normalize it for regression and use pytest-regression on this dict

**Pull request merged**
